# Example highlight queries for SQL

; Keywords
"SELECT" @keyword
"FROM" @keyword
"WHERE" @keyword
"JOIN" @keyword
"INNER" @keyword
"LEFT" @keyword
"RIGHT" @keyword
"OUTER" @keyword
"ON" @keyword
"GROUP" @keyword
"BY" @keyword
"HAVING" @keyword
"ORDER" @keyword
"ASC" @keyword
"DESC" @keyword
"LIMIT" @keyword
"OFFSET" @keyword
"INSERT" @keyword
"INTO" @keyword
"VALUES" @keyword
"UPDATE" @keyword
"SET" @keyword
"DELETE" @keyword
"CREATE" @keyword
"DROP" @keyword
"ALTER" @keyword
"TABLE" @keyword
"INDEX" @keyword
"VIEW" @keyword
"DATABASE" @keyword
"SCHEMA" @keyword
"CONSTRAINT" @keyword
"PRIMARY" @keyword
"FOREIGN" @keyword
"KEY" @keyword
"REFERENCES" @keyword
"NOT" @keyword
"NULL" @keyword
"DEFAULT" @keyword
"AUTO_INCREMENT" @keyword
"UNIQUE" @keyword
"CHECK" @keyword
"AND" @keyword
"OR" @keyword
"IN" @keyword
"BETWEEN" @keyword
"LIKE" @keyword
"IS" @keyword
"EXISTS" @keyword
"CASE" @keyword
"WHEN" @keyword
"THEN" @keyword
"ELSE" @keyword
"END" @keyword
"BEGIN" @keyword
"COMMIT" @keyword
"ROLLBACK" @keyword
"TRANSACTION" @keyword

; Data types
"INT" @type.builtin
"INTEGER" @type.builtin
"BIGINT" @type.builtin
"SMALLINT" @type.builtin
"TINYINT" @type.builtin
"DECIMAL" @type.builtin
"NUMERIC" @type.builtin
"FLOAT" @type.builtin
"DOUBLE" @type.builtin
"REAL" @type.builtin
"CHAR" @type.builtin
"VARCHAR" @type.builtin
"TEXT" @type.builtin
"DATE" @type.builtin
"TIME" @type.builtin
"TIMESTAMP" @type.builtin
"DATETIME" @type.builtin
"BOOLEAN" @type.builtin
"BOOL" @type.builtin
"BINARY" @type.builtin
"BLOB" @type.builtin

; Functions
"COUNT" @function.builtin
"SUM" @function.builtin
"AVG" @function.builtin
"MIN" @function.builtin
"MAX" @function.builtin
"LENGTH" @function.builtin
"SUBSTRING" @function.builtin
"CONCAT" @function.builtin
"UPPER" @function.builtin
"LOWER" @function.builtin
"TRIM" @function.builtin
"NOW" @function.builtin
"CURDATE" @function.builtin
"CURTIME" @function.builtin

; Identifiers
(identifier) @variable

; Strings
(string_literal) @string

; Numbers
(number) @number

; Comments
(comment) @comment

; Operators
"=" @operator
"!=" @operator
"<>" @operator
"<" @operator
">" @operator
"<=" @operator
">=" @operator
"+" @operator
"-" @operator
"*" @operator
"/" @operator
"%" @operator

; Punctuation
"(" @punctuation.bracket
")" @punctuation.bracket
";" @punctuation.delimiter
"," @punctuation.delimiter
"." @punctuation.delimiter